export interface Env {
  DB: D1Database;
  ADMIN_TOKEN: string;

  // Optional internal service binding to self (configured by CI deploy).
  SELF?: Fetcher;

  // Optional dev-only trace secret. If set, trace headers are honored only when
  // callers present `X-Uptimer-Trace-Token`.
  UPTIMER_TRACE_TOKEN?: string;
  TRACE_TOKEN?: string;
  UPTIMER_HOMEPAGE_RESIDUAL_TRACE?: string;
  UPTIMER_SCHEDULED_STATUS_REFRESH?: string;
  UPTIMER_TRACE_TIMINGS?: string;
  UPTIMER_HOMEPAGE_RELEASE_LOCK?: string;
  UPTIMER_HOMEPAGE_WRITE_LEASE_CHECK?: string;
  UPTIMER_HOMEPAGE_PAYLOAD_SNAPSHOT_WRITE?: string;
  UPTIMER_PUBLIC_MONITOR_FRAGMENT_WRITES?: string;
  UPTIMER_PUBLIC_HOMEPAGE_ARTIFACT_FRAGMENT_WRITES?: string;
  UPTIMER_PUBLIC_MONITOR_UPDATE_FRAGMENT_WRITES?: string;
  UPTIMER_PUBLIC_SHARDED_HOMEPAGE_RUNTIME_SEED?: string;
  UPTIMER_MONITOR_RUNTIME_UPDATE_FRAGMENT_MAX_AGE_SECONDS?: string;
  UPTIMER_SCHEDULED_RUNTIME_FRAGMENT_REFRESH?: string;
  UPTIMER_PUBLIC_SHARDED_ASSEMBLER?: string;
  UPTIMER_PUBLIC_SHARDED_FRAGMENT_SEED?: string;
  UPTIMER_PUBLIC_SHARDED_SNAPSHOT_PUBLISH?: string;
  UPTIMER_SCHEDULED_SHARDED_ASSEMBLER?: string;
  UPTIMER_SCHEDULED_SHARDED_FRAGMENT_SEED?: string;
  UPTIMER_SCHEDULED_SHARDED_PUBLISH?: string;
  UPTIMER_SCHEDULED_SHARDED_SKIP_HOMEPAGE_REFRESH?: string;
  UPTIMER_SCHEDULED_SHARDED_CONTINUATION?: string;
  UPTIMER_SHARDED_CONTINUATION_DIAGNOSTICS?: string;
  UPTIMER_SHARDED_RUNTIME_UPDATE_BATCH_SIZE?: string;
  UPTIMER_SHARDED_ASSEMBLER_MODE?: string;
  UPTIMER_SHARDED_FRAGMENT_SEED_BATCH_SIZE?: string;
  UPTIMER_SCHEDULED_HOMEPAGE_DIRECT?: string;
  UPTIMER_TRUST_SCHEDULED_RUNTIME_UPDATES?: string;
  UPTIMER_INTERNAL_SCHEDULED_BATCH_SIZE?: string;
  UPTIMER_INTERNAL_SCHEDULED_BATCH_CONCURRENCY?: string;
  UPTIMER_INTERNAL_SCHEDULED_CHECK_BATCH_TIMEOUT_MS?: string;
  UPTIMER_INTERNAL_CHECK_BATCH_FRAGMENT_WRITE_SPLIT?: string;
  UPTIMER_INTERNAL_CHECK_BATCH_DIAGNOSTICS?: string;
  UPTIMER_INTERNAL_CHECK_BATCH_TRUST_SCHEDULER_LEASE?: string;
  UPTIMER_SCHEDULED_REFRESH_LOGS?: string;

  // In-memory, per-instance rate limit for admin endpoints.
  // Keep optional so older deployments don't break.
  ADMIN_RATE_LIMIT_MAX?: string;
  ADMIN_RATE_LIMIT_WINDOW_SEC?: string;
}
